url: https://veterina-smichov.github.io/
siteName: Veterina Smíchov
divider: –
description: 'Veterinární ambulance pro malá zvířata kousek od Anděla: Na Skalce 991/27. Prevence, diagnostika, operace i konzultace zdravotního stavu koček, psů, králíků, morčat a dalších malých savců.'
robots: false
ogImage: /assets/images/cms-managed/og-image.min.png
lang: cs
locale: cs-CZ
author: MVDr. Jana Lukešová
